import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

// Configure Roboto
const roboto = Roboto({
  weight: ["400", "700"], // optional: include the weights you need
  subsets: ["latin"],
  variable: "--font-roboto", // optional: for CSS variables
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}> {/* OR roboto.className */}
        {children}
      </body>
    </html>
  );
}
